apiVersion: batch/v1
kind: Job
metadata:
    name: batch-job
spec:
    template:
        metadata:
            labels:
                app: myjob
        spec:
            restartPolicy: OnFailure
            containers:
                - name: myjob
                  image: hanhiver/myjob

