apiVersion: v1
kind: Pod
metadata:
    name: myjob-env
spec:
    containers:
        - image: hanhiver/myjob_env
          name: generator
          env:
              - name: INTERVAL
                valueFrom:
                    configMapKeyRef:
                        name: myconfigmap
                        key: sleep_time


