apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
    name: mytest
spec:
    replicas: 2
    selector:
        matchLabels:
            app: mytest
    template:
        metadata:
            labels:
                app: mytest
        spec:
            containers:
                - name: mytest
                  image: hanhiver/mytest
