apiVersion: v1
kind: ReplicationController
metadata:
    name: mytest
spec:
    replicas: 2
    selector:
        app: mytest
    template:
        metadata:
            labels:
                app: mytest
        spec:
            containers:
                - name: mytest
                  image: hanhiver/mytest
                  ports:
                      - containerPort: 5000

