apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mytest-v1
spec:
  replicas: 1
  template: 
    metadata:
      name: mytest
      labels:
        app: mytest
    spec:
      containers:
        - image: hanhiver/mytest:v1
          name: mytest-v1
        - image: tutum/curl
          name: curl
          command: ["sleep", "999999"]
---
apiVersion: v1
kind: Service
metadata:
  name: mytest
spec:
  type: LoadBalancer
  selector:
    app: mytest
  ports:
    - port: 5001
      targetPort: 5000

